import React, {useEffect, useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as Dialog from '@radix-ui/react-dialog';
import * as Tabs from '@radix-ui/react-tabs';
import Fuse from 'fuse.js';
import {ArrowUpRight, ArrowRight, ArrowDown, Search, Bookmark, X, Plus, Check, SlidersHorizontal, LayoutGrid, List, Globe2, Code2, Layers3, BookOpen, GitCompareArrows, Download, Copy, ExternalLink, Github, CircleHelp, Menu, ChevronDown, Sparkles, Compass, RotateCcw, CheckCircle2} from 'lucide-react';
import data from './data.json';
import './style.css';

const categories=['全部','平台规范','企业产品','公共服务','行业系统','组件框架','构建工具'];
const categoriesEN={'全部':'ALL SYSTEMS','平台规范':'PLATFORM','企业产品':'ENTERPRISE','公共服务':'PUBLIC SERVICE','行业系统':'INDUSTRY','组件框架':'COMPONENTS','构建工具':'TOOLING'};
const storageKey='form-index:favorites:v1';
const fuse=new Fuse(data,{keys:['name','org','category','description','region','stack','tags'],threshold:0.28,ignoreLocation:true});
const routes=[
 {id:'foundations',number:'01',title:'从设计原则，到完整体系',desc:'适合建立设计系统认知。先理解为什么，再研究怎样落地。',ids:[1,2,4,8],steps:['读设计原则与基础样式','拆解组件、状态和交互规则','对照真实场景与研究依据'],color:'olive'},
 {id:'build',number:'02',title:'从一套变量，到可用产品',desc:'适合搭建自己的组件库。让设计语言成为可复用的工具。',ids:[48,50,45,49],steps:['用 DTCG 定义设计变量','用 Style Dictionary 衔接代码','组合 Radix，并用 Storybook 展示状态'],color:'lavender'},
 {id:'workbench',number:'03',title:'把复杂业务，设计得清楚',desc:'适合企业产品与工作台。围绕真实任务组织信息与操作。',ids:[13,16,5,19],steps:['比较列表、筛选与批量操作','研究错误、空状态和反馈','组合成完整业务流程'],color:'warm'}
];
function savedIds(){try{const v=JSON.parse(localStorage.getItem(storageKey)||'[]');return Array.isArray(v)?v.filter(id=>data.some(d=>d.id===id)):[];}catch{return [];}}
function initialQuery(){const p=new URLSearchParams(location.search);return {q:p.get('q')||'',cat:categories.includes(p.get('category'))?p.get('category'):'全部',status:['开源','公开规范','公开源码','源码可见','许可需区分','旧仓库归档','实现维护中'].includes(p.get('status'))?p.get('status'):'全部状态',sort:p.get('sort')==='name'?'name':'rank',item:data.find(d=>d.id===Number(p.get('item')))||null};}
const initial=initialQuery();
const OutLink=({href,children,className='',...props})=><a href={href} target="_blank" rel="noopener noreferrer" className={className} {...props}>{children}</a>;
function Mark({item,small=false}){return <span aria-hidden="true" className={`mark ${small?'small':''}`} style={{'--brand':item.color}}>{item.mark}</span>;}
function Brand(){return <a className="brand" href="#top" aria-label="形序，回到顶部"><span className="brand-symbol" aria-hidden="true"><i/><i/><i/><i/></span><span>形序<span className="brand-en">Design Index</span></span></a>;}
function Cover({item,featured=false}){
 return <div className={`art art-${item.id%6} ${featured?'featured-art':''}`} style={{'--brand':item.color}} aria-hidden="true">
   <span className="art-grid"/><span className="art-label">{categoriesEN[item.category]}</span><span className="art-index">{String(item.id).padStart(2,'0')}</span>
   <div className="art-composition"><span className="shape one"/><span className="shape two"/><span className="shape three"/><span className="shape four"/><span className="shape five"/><span className="art-letter">{item.mark}</span></div>
   <span className="art-bottom">FORM / SYSTEM / EXPERIENCE</span>
 </div>;
}
function App(){
 const [q,setQ]=useState(initial.q),[category,setCategory]=useState(initial.cat),[status,setStatus]=useState(initial.status),[sort,setSort]=useState(initial.sort);
 const [favorites,setFavorites]=useState(savedIds),[onlySaved,setOnlySaved]=useState(false),[view,setView]=useState('grid'),[limit,setLimit]=useState(12);
 const [compare,setCompare]=useState([]),[modal,setModal]=useState(initial.item?{type:'detail',item:initial.item}:null),[toast,setToast]=useState(''),[menuOpen,setMenuOpen]=useState(false);
 const [demoTone,setDemoTone]=useState('purple');
 const searchRef=useRef(null),lastFocus=useRef(null);
 const filtered=useMemo(()=>{
   const source=q.trim()?fuse.search(q.trim()).map(r=>r.item):data;
   const result=source.filter(d=>(category==='全部'||d.category===category)&&(status==='全部状态'||d.status===status)&&(!onlySaved||favorites.includes(d.id)));
   return sort==='name'?[...result].sort((a,b)=>a.name.localeCompare(b.name)):q.trim()?result:[...result].sort((a,b)=>a.id-b.id);
 },[q,category,status,onlySaved,favorites,sort]);
 useEffect(()=>setLimit(12),[q,category,status,sort,onlySaved]);
 useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify(favorites));}catch{}},[favorites]);
 useEffect(()=>{
   const p=new URLSearchParams();if(q)p.set('q',q);if(category!=='全部')p.set('category',category);if(status!=='全部状态')p.set('status',status);if(sort==='name')p.set('sort','name');if(modal?.type==='detail')p.set('item',modal.item.id);
   try{history.replaceState(null,'',`${location.pathname}${p.size?'?'+p:''}${location.hash}`);}catch{}
 },[q,category,status,sort,modal]);
 useEffect(()=>{const onKey=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setModal(null);document.getElementById('explore').scrollIntoView();searchRef.current?.focus();}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3200);return()=>clearTimeout(t);},[toast]);
 function openModal(value){lastFocus.current=document.activeElement;setModal(value);setMenuOpen(false);}
 function favorite(id){const exists=favorites.includes(id);setFavorites(v=>exists?v.filter(x=>x!==id):[...v,id]);setToast(exists?'已从收藏移除':'已加入收藏，仅保存在当前浏览器');}
 function compareItem(id){if(!compare.includes(id)&&compare.length>=3){setToast('最多对比 3 个项目，请先移除一个');return;}setCompare(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);}
 function clear(){setQ('');setCategory('全部');setStatus('全部状态');setOnlySaved(false);setSort('rank');}
 function showSaved(){setOnlySaved(v=>!v);setMenuOpen(false);document.getElementById('explore').scrollIntoView({behavior:'smooth'});}
 async function share(){try{await navigator.clipboard.writeText(location.href);setToast('当前页面链接已复制');}catch{setToast('请复制浏览器地址栏中的链接');}}
 function download(){const rows=data.map(d=>`| ${d.id} | [${d.name}](${d.url}) | ${d.description} | ${d.source?'[源码]('+d.source+')':'公开规范'} | ${d.status} |`);const body='# 形序 · 全球设计系统精选 50\n\n资料核对：2026-10-02。精选索引，不是官方排名。\n\n| # | 项目 | 学习重点 | 源码 | 状态 |\n|---|---|---|---|---|\n'+rows.join('\n');const u=URL.createObjectURL(new Blob([body],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='形序-设计系统精选50.md';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);setToast('完整清单已生成下载');}
 const hasFilters=q||category!=='全部'||status!=='全部状态'||onlySaved;
 const compared=data.filter(d=>compare.includes(d.id));
 return <>
  <a className="skip" href="#explore">跳到设计系统索引</a>
  <header className="site-header" id="top"><div className="nav-inner"><Brand/><nav className={menuOpen?'nav-links open':'nav-links'} aria-label="主导航"><a href="#explore" onClick={()=>setMenuOpen(false)}>探索系统</a><a href="#routes" onClick={()=>setMenuOpen(false)}>学习路线</a><button onClick={()=>openModal({type:'about'})}>关于索引 <ArrowUpRight size={13}/></button></nav><div className="nav-actions"><button className={`save-nav ${onlySaved?'active':''}`} onClick={showSaved} aria-label={`我的收藏 ${favorites.length}`} aria-pressed={onlySaved}><Bookmark size={16}/><span>我的收藏</span><b>{favorites.length}</b></button><button className="mobile-menu icon-btn" aria-label={menuOpen?'收起菜单':'打开菜单'} aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}>{menuOpen?<X size={21}/>:<Menu size={21}/>}</button></div></div></header>
  <main>
   <section className="hero shell">
    <div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> A FIELD GUIDE TO DESIGN SYSTEMS <span className="edition">VOL. 01 / 2026</span></div>
     <h1>让好设计，<br/><span>有迹可循。</span><span className="title-star" aria-hidden="true">✳</span></h1>
     <p className="hero-desc">从设计原则，到每一个交互细节。<br/>探索全球 50 个设计系统，找到适合你的下一步。</p>
     <div className="hero-actions"><a className="pill-primary" href="#explore">开始探索 <span>50</span><i><ArrowUpRight size={19}/></i></a><a className="text-link" href="#routes">找到学习起点 <ArrowRight size={16}/></a></div>
     <div className="hero-proof"><div className="proof-marks" aria-hidden="true"><span>IBM</span><span>G</span><span className="windows-mark">▦</span><span>A</span></div><div><strong>来自真实产品的设计实践</strong><small>官方规范 · 开源项目 · 实用工具</small></div></div>
    </div>
    <div className={`hero-study tone-${demoTone}`}>
     <div className="study-top"><span className="mono">THE ANATOMY OF A SYSTEM</span><span className="study-dot"/></div>
     <div className="study-big">Aa<span>形</span><small>好的秩序，自有表达。</small></div>
     <div className="study-palette"><span/><span/><span/><span/><span/></div>
     <div className="study-rule"><span>01 / 基础</span><span>02 / 组件</span><span>03 / 体验</span></div>
     <div className="study-components"><div className="spec-button">建立你的设计语言 <ArrowUpRight size={17}/></div><span className="spec-check"><Check size={15}/> 有据可循</span></div>
     <div className="study-bottom"><span>同一套规则，不同的表达</span><div role="group" aria-label="预览配色"><button aria-label="深紫配色" aria-pressed={demoTone==='purple'} className="tone-purple" onClick={()=>setDemoTone('purple')}/><button aria-label="橄榄配色" aria-pressed={demoTone==='olive'} className="tone-olive" onClick={()=>setDemoTone('olive')}/><button aria-label="蓝灰配色" aria-pressed={demoTone==='blue'} className="tone-blue" onClick={()=>setDemoTone('blue')}/></div></div>
     <span className="study-annotation">从规则，到创造 <span>↗</span></span>
    </div>
   </section>
   <div className="index-strip shell"><div><span className="mono">01 — 50</span><span>精选全球设计实践</span></div><p>少一点漫无目的，<span>多一点有据可循。</span></p><a href="#explore" aria-label="向下浏览索引"><ArrowDown size={20}/></a></div>
   <section className="explore shell" id="explore" aria-labelledby="explore-heading">
    <div className="section-heading"><div><div className="eyebrow">THE COLLECTION / 精选索引</div><h2 id="explore-heading">你的下一份设计参考<span className="sup-count">50</span></h2></div><p>读懂规范，也看见规范背后的方法。</p></div>
    <div className="search-row"><div className="search-box"><Search size={21}/><input ref={searchRef} id="search" aria-label="搜索设计系统" placeholder="搜索名称、场景或技术栈，如 Carbon、表单、React…" value={q} onChange={e=>setQ(e.target.value)}/>{q?<button className="icon-btn" aria-label="清除搜索" onClick={()=>setQ('')}><X size={17}/></button>:<kbd>⌘ K</kbd>}</div><button className={`saved-filter ${onlySaved?'active':''}`} aria-pressed={onlySaved} onClick={()=>setOnlySaved(v=>!v)}><Bookmark size={16} fill={onlySaved?'currentColor':'none'}/><span>只看收藏</span></button></div>
    <div className="category-row" role="group" aria-label="按应用方向筛选">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={c===category?'active':''} aria-pressed={c===category}>{c}<span>{c==='全部'?50:data.filter(d=>d.category===c).length}</span></button>)}</div>
    <div className="results-toolbar"><p role="status">{hasFilters?'找到':'浏览'} <strong>{filtered.length}</strong> 个{onlySaved?'收藏':'设计资源'}{hasFilters&&<button className="reset-link" onClick={clear}>重置筛选 <RotateCcw size={12}/></button>}</p><div className="toolbar-controls"><label className="select-wrapper"><SlidersHorizontal size={14}/><span className="sr-only">源码状态</span><select aria-label="源码状态" value={status} onChange={e=>setStatus(e.target.value)}>{['全部状态','开源','公开规范','公开源码','源码可见','许可需区分','旧仓库归档','实现维护中'].map(v=><option key={v}>{v}</option>)}</select><ChevronDown size={12}/></label><label className="select-wrapper"><span className="sr-only">排序方式</span><select aria-label="排序方式" value={sort} onChange={e=>setSort(e.target.value)}><option value="rank">推荐顺序</option><option value="name">名称 A—Z</option></select><ChevronDown size={12}/></label><div className="view-toggle"><button aria-label="卡片视图" aria-pressed={view==='grid'} onClick={()=>setView('grid')}><LayoutGrid size={16}/></button><button aria-label="列表视图" aria-pressed={view==='list'} onClick={()=>setView('list')}><List size={17}/></button></div></div></div>
    {filtered.length>0?<div className={`resource-grid ${view==='list'?'list-view':''}`}>{filtered.slice(0,limit).map(item=><article className="resource-card" key={item.id} data-resource={item.id}>
     <div className="card-cover"><button className="cover-button" onClick={()=>openModal({type:'detail',item})} aria-label={`查看 ${item.name} 详情`}><Cover item={item}/></button><button className={`favorite-btn ${favorites.includes(item.id)?'saved':''}`} aria-label={`${favorites.includes(item.id)?'取消收藏':'收藏'} ${item.name}`} aria-pressed={favorites.includes(item.id)} onClick={()=>favorite(item.id)}><Bookmark size={17} fill={favorites.includes(item.id)?'currentColor':'none'}/></button></div>
     <div className="card-body"><div className="card-identity"><Mark item={item} small/><div><button className="card-title" onClick={()=>openModal({type:'detail',item})}>{item.name}<ArrowUpRight size={16}/></button><p>{item.org}<span> / {item.region}</span></p></div></div><p className="card-description">{item.description}</p><div className="card-tags"><span>{item.category}</span><span>{item.stack.split(' / ')[0]}</span></div><div className="card-bottom"><span className={`status-badge status-${item.status==='开源'?'open':['旧仓库归档','实现维护中'].includes(item.status)?'caution':'neutral'}`}><i/>{item.status}</span><button className={`compare-btn ${compare.includes(item.id)?'selected':''}`} aria-pressed={compare.includes(item.id)} aria-label={`${compare.includes(item.id)?'取消对比':'对比'} ${item.name}`} onClick={()=>compareItem(item.id)}>{compare.includes(item.id)?<Check size={14}/>:<Plus size={14}/>}<span>对比</span></button></div></div>
    </article>)}</div>:<div className="empty-state"><Compass size={42} strokeWidth={1}/><h3>{onlySaved&&!favorites.length?'把下一份灵感，留在这里':'暂时没有匹配的设计系统'}</h3><p>{onlySaved&&!favorites.length?'点击卡片上的书签，即可建立你的参考书架。':'试试更短的关键词，或放宽分类和源码状态。'}</p><button className="pill-outline" onClick={clear}>浏览全部 50 个 <ArrowRight size={16}/></button></div>}
    {filtered.length>0&&<div className="load-row"><span>已展示 {Math.min(limit,filtered.length)} / {filtered.length}</span>{limit<filtered.length?<button className="pill-outline" onClick={()=>setLimit(v=>v+12)}>继续探索 <ArrowDown size={16}/></button>:<p>你已浏览全部结果 <Check size={14}/></p>}<span>每一个，都有可追溯的来源</span></div>}
   </section>
   <section className="routes-section" id="routes"><div className="shell"><div className="section-heading"><div><div className="eyebrow">A GOOD PLACE TO START / 学习路线</div><h2>不必从 50 个开始。</h2></div><p>选一个目标，沿着问题去学习。</p></div><div className="route-grid">{routes.map(route=><button className={`route-card ${route.color}`} key={route.id} onClick={()=>openModal({type:'route',route})}><span className="route-top"><span className="mono">PATH {route.number}</span><ArrowUpRight size={23}/></span><h3>{route.title}</h3><p>{route.desc}</p><div className="route-brands">{route.ids.slice(0,3).map(id=><Mark key={id} item={data[id-1]} small/>)}<span>4 个学习起点 <ArrowRight size={14}/></span></div></button>)}</div></div></section>
   <section className="closing shell"><span className="closing-symbol" aria-hidden="true">✳</span><div><h2>把规范读薄，把设计做深。</h2><p>收藏、比较、实践。让参考真正成为你的判断力。</p></div><button className="pill-primary" onClick={download}>带走完整清单 <Download size={17}/></button></section>
  </main>
  <footer className="site-footer shell"><div><Brand/><p>连接设计原则与真实产品。</p></div><div className="footer-meta"><p>50 个精选资源 · 资料核对于 2026.10.02</p><span>独立整理，非官方排名。项目名称归各权利人所有。</span></div><button onClick={()=>openModal({type:'about'})}>关于与来源 <ArrowUpRight size={14}/></button></footer>
  {compare.length>0&&<div className="compare-tray"><span className="tray-label"><GitCompareArrows size={18}/><strong>对比清单</strong><small>{compare.length} / 3</small></span><div className="tray-items">{compared.map(item=><span key={item.id}><Mark item={item} small/><b>{item.name}</b><button aria-label={`移除 ${item.name} 的对比`} onClick={()=>compareItem(item.id)}><X size={13}/></button></span>)}</div><button className="tray-clear" onClick={()=>setCompare([])}>清空</button><button className="pill-primary" disabled={compare.length<2} onClick={()=>openModal({type:'compare'})}>开始对比 <ArrowRight size={16}/></button></div>}
  {toast&&<div className="toast" role="status"><CheckCircle2 size={17}/>{toast}</div>}
  <Dialog.Root open={!!modal} onOpenChange={open=>{if(!open)setModal(null);}}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content aria-modal="true" className={`modal-content ${modal?.type==='compare'?'comparison-modal':''}`} onCloseAutoFocus={e=>{e.preventDefault();if(lastFocus.current?.isConnected)lastFocus.current.focus();else searchRef.current?.focus();}}>
    <Dialog.Close className="modal-close icon-btn" aria-label="关闭弹窗"><X size={21}/></Dialog.Close>
    {modal?.type==='detail'&&<><div className="detail-cover"><Cover item={modal.item} featured/></div><div className="detail-content"><div className="detail-head"><div><span className="eyebrow">NO. {String(modal.item.id).padStart(2,'0')} / {modal.item.category}</span><Dialog.Title>{modal.item.name}</Dialog.Title><Dialog.Description>{modal.item.org} · {modal.item.region} · {modal.item.stack}</Dialog.Description></div><button className={`icon-btn detail-save ${favorites.includes(modal.item.id)?'active':''}`} aria-label={`${favorites.includes(modal.item.id)?'取消收藏':'收藏'} ${modal.item.name}`} onClick={()=>favorite(modal.item.id)}><Bookmark fill={favorites.includes(modal.item.id)?'currentColor':'none'} size={20}/></button></div>
     <Tabs.Root defaultValue="overview" className="detail-tabs"><Tabs.List aria-label="项目资料"><Tabs.Trigger value="overview">项目概览</Tabs.Trigger><Tabs.Trigger value="learn">怎么学习</Tabs.Trigger></Tabs.List><Tabs.Content value="overview"><p className="detail-lead">{modal.item.description}。</p><div className="facts"><div><small>应用方向</small><strong>{modal.item.category}</strong></div><div><small>实现 / 规范</small><strong>{modal.item.stack}</strong></div><div><small>源码状态</small><strong>{modal.item.status}</strong></div></div>{modal.item.note&&<div className="source-note"><CircleHelp size={18}/><p>{modal.item.note}</p></div>}<p className="verification-note">资料核对：{modal.item.checked} · 入选理由为编辑判断。视觉封面为索引示意，非官网截图。</p></Tabs.Content><Tabs.Content value="learn"><p className="detail-lead">带着一个具体问题去读，比一次看完更有效。</p><ol className="learning-steps"><li><span>01</span><div><strong>先选一个研究重点</strong><p>从「{modal.item.tags[0]}」切入，记录它解决的用户问题。</p></div></li><li><span>02</span><div><strong>对照使用条件与状态</strong><p>比较默认、选中、禁用、错误等情况，查看官方示例与使用边界。</p></div></li><li><span>03</span><div><strong>在自己的场景中验证</strong><p>选一个真实页面尝试应用，再与其他系统比较取舍。</p></div></li></ol><p className="verification-note">以上为本站建议的学习顺序，不代表项目官方教程。</p></Tabs.Content></Tabs.Root>
     <div className="detail-actions"><OutLink href={modal.item.url} className="pill-primary">访问官方文档 <ArrowUpRight size={17}/></OutLink>{modal.item.source&&<OutLink href={modal.item.source} className="pill-outline"><Code2 size={16}/>查看源码</OutLink>}<button className="icon-btn" aria-label="复制项目链接" onClick={share}><Copy size={17}/></button><button className="pill-subtle" onClick={()=>compareItem(modal.item.id)}>{compare.includes(modal.item.id)?<Check size={15}/>:<Plus size={15}/>}加入对比</button></div></div></>}
    {modal?.type==='compare'&&<div className="standard-modal"><span className="eyebrow">SIDE BY SIDE / 项目对比</span><Dialog.Title>找到更适合你的那一个。</Dialog.Title><Dialog.Description>按应用场景与源码边界比较，选择适合当前问题的资源。</Dialog.Description><div className="compare-scroll"><table><thead><tr><th>比较维度</th>{compared.map(d=><th key={d.id}><Mark item={d}/><strong>{d.name}</strong><small>{d.org}</small></th>)}</tr></thead><tbody>{[['应用方向','category'],['技术 / 规范','stack'],['参考价值','description'],['源码状态','status'],['使用说明','note']].map(([title,key])=><tr key={key}><th scope="row">{title}</th>{compared.map(d=><td key={d.id}>{d[key]||'查看项目官方文档与仓库许可。'}</td>)}</tr>)}<tr><th scope="row">官方入口</th>{compared.map(d=><td key={d.id}><OutLink href={d.url}>官方文档 <ArrowUpRight size={14}/></OutLink>{d.source&&<OutLink href={d.source}>源码仓库 <ArrowUpRight size={14}/></OutLink>}</td>)}</tr></tbody></table></div></div>}
    {modal?.type==='route'&&<div className="standard-modal"><span className="eyebrow">PATH {modal.route.number} / 学习路线</span><Dialog.Title>{modal.route.title}</Dialog.Title><Dialog.Description>{modal.route.desc}</Dialog.Description><ol className="route-steps">{modal.route.steps.map((step,i)=><li key={step}><span>0{i+1}</span>{step}</li>)}</ol><h3>沿途的 4 个参考</h3><div className="route-resources">{modal.route.ids.map(id=><button key={id} onClick={()=>setModal({type:'detail',item:data[id-1]})}><Mark item={data[id-1]}/><span><strong>{data[id-1].name}</strong><small>{data[id-1].description}</small></span><ArrowUpRight size={18}/></button>)}</div><p className="verification-note">这是本站整理的学习建议，可按项目需要调整。</p></div>}
    {modal?.type==='about'&&<div className="standard-modal about-modal"><span className="eyebrow">ABOUT THE INDEX / 关于形序</span><Dialog.Title>一份有来源的设计参考。</Dialog.Title><Dialog.Description>形序收录 50 个设计规范、设计系统、组件库与构建工具，帮助你从阅读走向实践。</Dialog.Description><div className="about-principles"><div><Layers3 size={22}/><h3>按问题寻找</h3><p>按平台、业务、公共服务等方向浏览，避免把风格相似当成场景适合。</p></div><div><BookOpen size={22}/><h3>回到一手来源</h3><p>每个条目提供官方文档入口。有源码的项目同时提供对应仓库。</p></div><div><Code2 size={22}/><h3>区分使用边界</h3><p>公开规范、开源组件、源码可见与归档项目分开标注。</p></div></div><div className="about-note"><h3>这份索引如何整理？</h3><p>资料核对于 2026 年 10 月 2 日。推荐顺序综合规范完整度、组件覆盖、无障碍与应用价值，是编辑选择，不是官方排名或实时热度榜。</p><p>部分官网依赖 JavaScript 或限制抓取，使用官方仓库补充核对；本站未逐个安装运行全部项目。收藏保存在当前浏览器，不会上传或跨设备同步。</p><p>网站视觉参考 LightVela 的浅色表面、深紫黑与橄榄色、胶囊按钮及细竖纹。交互基于 <OutLink href="https://github.com/radix-ui/primitives">Radix UI</OutLink>，图标来自 <OutLink href="https://github.com/lucide-icons/lucide">Lucide</OutLink>。封面为原创索引示意，不是项目官方视觉。</p></div><button className="pill-primary" onClick={download}>下载 50 项完整清单 <Download size={17}/></button></div>}
   </Dialog.Content></Dialog.Portal></Dialog.Root>
 </>;
}
createRoot(document.getElementById('root')).render(<App/>);
